# Generated by Django 3.2.7 on 2021-09-14 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0002_rename_books_book'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, choices=[(0, 'Unknown'), (1, 'Processed'), (2, 'Paid')], default='', max_length=36, null=True, unique=True),
        ),
    ]
