# Generated by Django 3.2.7 on 2021-09-16 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0007_book_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='isbn',
            name='ISBN_10',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='isbn',
            name='ISBN_13',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='demo.book')),
            ],
        ),
    ]
